"""Report and dimension registry."""

from __future__ import annotations

from app.services.reports.config import (
    ATR_BUCKETS,
    DAY_TYPE_LABELS,
    DAILY_PNL_STATE_BUCKETS,
    DURATION_BUCKETS_SEC,
    ENTRY_ATR_BUCKETS,
    ENTRY_PRICE_BUCKETS,
    GAP_BUCKETS,
    IMPULSE_BUCKETS,
    INITIAL_RISK_BUCKETS,
    MARKET_GAP_BUCKETS,
    MARKET_MOVEMENT_BUCKETS,
    MFE_R_BUCKETS,
    MAE_R_BUCKETS,
    EXIT_EFFICIENCY_BUCKETS,
    R_LEFT_BUCKETS,
    TIME_TO_MFE_BUCKETS,
    MFE_TO_EXIT_BUCKETS,
    PEAK_GIVEBACK_BUCKETS,
    MOVEMENT_BUCKETS,
    POSITION_VALUE_BUCKETS,
    PRIOR_RVOL_BUCKETS,
    QUANTITY_BUCKETS,
    RETRACEMENT_BUCKETS,
    RISK_PCT_EQUITY_BUCKETS,
    RVOL_BUCKETS,
    SECTIONS,
    SIGNAL_GAP_BUCKETS,
    SIGNAL_RVOL_BUCKETS,
    SMA_DIST_BUCKETS,
    STOP_DISTANCE_BUCKETS,
    TR_ATR_BUCKETS,
    VOLUME_BUCKETS,
    WEEKDAYS,
)
from app.services.analytics.r_distribution import R_BUCKETS

REPORT_DEFINITIONS = [
    # TIME
    {"key": "day_of_week", "title": "Performance by Day of Week", "section": "TIME", "feature": "day_of_week",
     "sort": [w[0] for w in WEEKDAYS], "default_metric": "net_pnl"},
    {"key": "entry_hour", "title": "Performance by Entry Hour", "section": "TIME", "feature": "entry_hour",
     "sort": [f"{h:02d}" for h in range(7, 16)] + ["16_plus"], "default_metric": "net_pnl"},
    {"key": "entry_30m", "title": "Performance by 30-Minute Entry Window", "section": "TIME", "feature": "entry_30m",
     "default_metric": "net_pnl"},
    {"key": "entry_15m", "title": "Performance by 15-Minute Entry Window", "section": "TIME", "feature": "entry_15m",
     "default_metric": "net_pnl"},
    {"key": "month", "title": "Performance by Calendar Month", "section": "TIME", "feature": "month",
     "default_metric": "net_pnl"},
    {"key": "week", "title": "Performance by Week", "section": "TIME", "feature": "week",
     "default_metric": "net_pnl"},
    {"key": "day_of_month", "title": "Performance by Day of Month", "section": "TIME", "feature": "day_of_month",
     "sort": [str(i) for i in range(1, 32)], "default_metric": "net_pnl"},
    {"key": "duration", "title": "Performance by Holding Duration", "section": "TIME", "feature": "duration",
     "sort": ["lt_60", "1_2", "2_5", "5_10", "10_20", "20_60", "60_plus"], "default_metric": "net_pnl"},
    {"key": "entry_hour_activity", "title": "Trade Count by Entry Hour", "section": "TIME", "feature": "entry_hour",
     "sort": [f"{h:02d}" for h in range(7, 16)] + ["16_plus"], "default_metric": "trade_count"},
    # TRADE
    {"key": "entry_price", "title": "Performance by Entry Price", "section": "TRADE", "feature": "entry_price",
     "sort": ["lt_2", "2_3", "3_5", "5_10", "10_20", "20_plus"], "default_metric": "net_pnl"},
    {"key": "quantity", "title": "Performance by Share Quantity", "section": "TRADE", "feature": "quantity",
     "sort": ["lt_100", "100_199", "200_499", "500_999", "1000_1999", "2000_plus"], "default_metric": "net_pnl"},
    {"key": "position_value", "title": "Performance by Position Value", "section": "TRADE", "feature": "position_value",
     "sort": ["lt_500", "500_1000", "1000_2500", "2500_5000", "5000_10000", "10000_plus"], "default_metric": "net_pnl"},
    {"key": "fill_count", "title": "Performance by Number of Fills", "section": "TRADE", "feature": "fill_count",
     "default_metric": "net_pnl"},
    {"key": "entry_style", "title": "Performance by Entry Style", "section": "TRADE", "feature": "entry_style",
     "default_metric": "net_pnl"},
    {"key": "exit_style", "title": "Performance by Exit Style", "section": "TRADE", "feature": "exit_style",
     "default_metric": "net_pnl"},
    # INSTRUMENT
    {"key": "symbol", "title": "Performance by Symbol", "section": "INSTRUMENT", "feature": "symbol",
     "default_metric": "net_pnl", "limit": 20},
    {"key": "symbol_avg", "title": "Symbol — Average Trade", "section": "INSTRUMENT", "feature": "symbol",
     "default_metric": "avg_trade", "min_sample_default": 2, "limit": 20},
    {"key": "symbol_winrate", "title": "Symbol — Win Rate", "section": "INSTRUMENT", "feature": "symbol",
     "default_metric": "win_rate", "min_sample_default": 2, "limit": 20},
    # INSTRUMENT — market enrichment (Step 4)
    {"key": "instrument_gap", "title": "Performance by Opening Gap %", "section": "INSTRUMENT",
     "feature": "opening_gap_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "description": "Regular-session open vs prior close."},
    {"key": "instrument_volume", "title": "Performance by Instrument Daily Volume", "section": "INSTRUMENT",
     "feature": "day_volume_bucket", "default_metric": "net_pnl", "availability_timing": "END_OF_DAY",
     "quality_requirement": "FULL_FEED"},
    {"key": "instrument_rvol50", "title": "Performance by Relative Volume (RVOL50)", "section": "INSTRUMENT",
     "feature": "rvol50_bucket", "default_metric": "net_pnl", "availability_timing": "END_OF_DAY",
     "quality_requirement": "FULL_FEED"},
    {"key": "instrument_prior_rvol", "title": "Performance by Prior-Day RVOL", "section": "INSTRUMENT",
     "feature": "prior_rvol_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "quality_requirement": "FULL_FEED"},
    {"key": "instrument_movement", "title": "Performance by Daily Stock Movement", "section": "INSTRUMENT",
     "feature": "movement_bucket", "default_metric": "net_pnl", "availability_timing": "END_OF_DAY"},
    {"key": "instrument_atr14", "title": "Performance by ATR(14)", "section": "INSTRUMENT",
     "feature": "atr14_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY"},
    {"key": "entry_vs_atr", "title": "Performance by Entry Extension vs ATR", "section": "INSTRUMENT",
     "feature": "entry_atr_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY"},
    {"key": "instrument_rel_vol", "title": "Performance by Relative Volatility (TR/ATR)", "section": "INSTRUMENT",
     "feature": "tr_atr_bucket", "default_metric": "net_pnl", "availability_timing": "END_OF_DAY"},
    {"key": "instrument_day_type", "title": "Performance by Instrument Day Type", "section": "INSTRUMENT",
     "feature": "day_type", "default_metric": "net_pnl", "availability_timing": "END_OF_DAY",
     "sort": ["trend_up", "trend_down", "inside_range", "outside_range"]},
    {"key": "entry_vs_sma20", "title": "Performance by Entry vs SMA20", "section": "INSTRUMENT",
     "feature": "entry_sma20_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY"},
    {"key": "entry_vs_sma50", "title": "Performance by Entry vs SMA50", "section": "INSTRUMENT",
     "feature": "entry_sma50_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY"},
    # MARKET
    {"key": "market_movement", "title": "Performance by Market Movement (SPY)", "section": "MARKET",
     "feature": "market_movement_bucket", "default_metric": "net_pnl", "availability_timing": "END_OF_DAY"},
    {"key": "market_gap", "title": "Performance by Market Gap (SPY)", "section": "MARKET",
     "feature": "market_gap_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY"},
    {"key": "market_day_type", "title": "Performance by Market Day Type (SPY)", "section": "MARKET",
     "feature": "market_day_type", "default_metric": "net_pnl", "availability_timing": "END_OF_DAY",
     "sort": ["trend_up", "trend_down", "inside_range", "outside_range"]},
    {"key": "source", "title": "Performance by Source", "section": "SOURCE", "feature": "source",
     "sort": ["MANUAL", "AUTO"], "default_metric": "net_pnl"},
    {"key": "direction", "title": "Performance by Direction", "section": "SOURCE", "feature": "direction",
     "sort": ["LONG", "SHORT"], "default_metric": "net_pnl"},
    {"key": "source_winrate", "title": "Win Rate by Source", "section": "SOURCE", "feature": "source",
     "sort": ["MANUAL", "AUTO"], "default_metric": "win_rate"},
    {"key": "direction_winrate", "title": "Win Rate by Direction", "section": "SOURCE", "feature": "direction",
     "sort": ["LONG", "SHORT"], "default_metric": "win_rate"},
    # BEHAVIOR
    {"key": "trade_number", "title": "Performance by Trade Number of Day", "section": "BEHAVIOR", "feature": "trade_number",
     "sort": ["1", "2", "3", "4", "5_plus"], "default_metric": "net_pnl"},
    {"key": "prev_outcome", "title": "Performance After Previous Completed Trade", "section": "BEHAVIOR",
     "feature": "prev_outcome", "sort": ["FIRST", "WIN", "LOSS", "BREAKEVEN"], "default_metric": "net_pnl"},
    {"key": "consec_losses", "title": "Performance After Consecutive Losses", "section": "BEHAVIOR",
     "feature": "consec_losses", "sort": ["0", "1", "2", "3_plus"], "default_metric": "net_pnl"},
    {"key": "daily_pnl_state", "title": "Performance by Daily P&L Before Entry", "section": "BEHAVIOR",
     "feature": "daily_pnl_state",
     "sort": ["lt_neg_200", "neg_200_50", "neg_50_50", "50_200", "gt_200"], "default_metric": "net_pnl"},
    # OUTCOMES
    {"key": "pnl_distribution", "title": "P&L Distribution", "section": "OUTCOMES", "feature": "pnl_bucket",
     "default_metric": "trade_count"},
    {"key": "outcome_composition", "title": "Winner / Loser / Breakeven Composition", "section": "OUTCOMES",
     "feature": "outcome", "sort": ["WIN", "LOSS", "BREAKEVEN"], "default_metric": "trade_count"},
    {"key": "pnl_sequence", "title": "Trade P&L Over Time", "section": "OUTCOMES", "feature": "_sequence",
     "chart_type": "line", "default_metric": "net_pnl"},
    {"key": "avg_trade_week", "title": "Average Trade by Week", "section": "OUTCOMES", "feature": "week",
     "default_metric": "avg_trade"},
    # EXECUTION (Step 8)
    {"key": "mfe_r_distribution", "title": "MFE Distribution", "section": "EXECUTION", "feature": "mfe_r_bucket",
     "sort": ["lt_0_5", "0_5_1", "1_1_5", "1_5_2", "2_3", "3_5", "5_plus"], "default_metric": "trade_count"},
    {"key": "mae_r_distribution", "title": "MAE Distribution", "section": "EXECUTION", "feature": "mae_r_bucket",
     "sort": ["lte_neg_2", "neg_2_1_5", "neg_1_5_1", "neg_1_0_75", "neg_0_75_0_5", "neg_0_5_0_25", "neg_0_25_0"],
     "default_metric": "trade_count"},
    {"key": "exit_efficiency_report", "title": "Performance by Exit Efficiency", "section": "EXECUTION",
     "feature": "exit_efficiency_bucket",
     "sort": ["lt_0", "0_25", "25_50", "50_75", "75_90", "90_100", "gt_100"], "default_metric": "trade_count"},
    {"key": "r_left_report", "title": "R Left on Table", "section": "EXECUTION", "feature": "r_left_bucket",
     "sort": ["lt_0", "0_0_5", "0_5_1", "1_2", "2_3", "3_plus"], "default_metric": "trade_count"},
    {"key": "time_to_mfe_report", "title": "Time to MFE", "section": "EXECUTION", "feature": "time_to_mfe_bucket",
     "sort": ["lt_60", "1_2", "2_5", "5_10", "10_20", "20_60", "60_plus"], "default_metric": "trade_count"},
    {"key": "time_to_mae_report", "title": "Time to MAE", "section": "EXECUTION", "feature": "time_to_mae_bucket",
     "sort": ["lt_60", "1_2", "2_5", "5_10", "10_20", "20_60", "60_plus"], "default_metric": "trade_count"},
    {"key": "mfe_to_exit_report", "title": "Time from MFE to Final Exit", "section": "EXECUTION",
     "feature": "mfe_to_exit_bucket",
     "sort": ["lt_60", "1_2", "2_5", "5_10", "10_20", "20_plus"], "default_metric": "trade_count"},
    {"key": "peak_giveback_report", "title": "Peak Giveback %", "section": "EXECUTION", "feature": "peak_giveback_bucket",
     "sort": ["lt_10", "10_25", "25_50", "50_75", "75_100", "gt_100"], "default_metric": "trade_count"},
    # STRATEGY (Step 5) — CONFIRMED links; missing values excluded (not "Other")
    {"key": "strategy_key", "title": "Performance by Strategy", "section": "STRATEGY", "feature": "strategy_key",
     "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY", "exclude_missing": True,
     "description": "Pine strategy key. CONFIRMED signal links only."},
    {"key": "strategy_version", "title": "Performance by Strategy Version", "section": "STRATEGY",
     "feature": "strategy_version", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True, "description": "Original Pine strategy_version string. Versions are not merged."},
    {"key": "signal_origin", "title": "Performance by Signal Origin", "section": "STRATEGY", "feature": "signal_origin",
     "sort": ["REALTIME", "HISTORICAL_REPLAY", "BACKTEST", "UNKNOWN"], "default_metric": "net_pnl",
     "availability_timing": "PRE_ENTRY", "exclude_missing": True},
    {"key": "setup_quality", "title": "Performance by Setup Quality", "section": "STRATEGY", "feature": "setup_quality",
     "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY", "exclude_missing": True,
     "description": "Pine setup quality at signal time. Missing quality is not bucketed as Other."},
    {"key": "signal_gap", "title": "Performance by Signal-Time Gap", "section": "STRATEGY", "feature": "signal_gap_bucket",
     "sort": [b[0] for b in SIGNAL_GAP_BUCKETS], "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True, "description": "Pine signal-time gap vs prior close. Not instrument opening gap."},
    {"key": "signal_rvol", "title": "Performance by Signal-Time RVOL", "section": "STRATEGY",
     "feature": "signal_rvol_bucket", "sort": [b[0] for b in SIGNAL_RVOL_BUCKETS], "default_metric": "net_pnl",
     "availability_timing": "PRE_ENTRY", "exclude_missing": True,
     "description": "Pine signal-time RVOL. Not instrument RVOL50 EOD."},
    {"key": "impulse", "title": "Performance by Initial Impulse", "section": "STRATEGY", "feature": "impulse_bucket",
     "sort": [b[0] for b in IMPULSE_BUCKETS], "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True},
    {"key": "retracement", "title": "Performance by Pullback Retracement", "section": "STRATEGY",
     "feature": "retracement_bucket", "sort": [b[0] for b in RETRACEMENT_BUCKETS], "default_metric": "net_pnl",
     "availability_timing": "PRE_ENTRY", "exclude_missing": True},
    {"key": "context_5m", "title": "Performance by 5-Minute Context", "section": "STRATEGY", "feature": "context_5m",
     "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY", "exclude_missing": True},
    {"key": "above_vwap", "title": "Performance by VWAP Condition", "section": "STRATEGY", "feature": "above_vwap",
     "sort": ["above", "not_above"], "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True},
    {"key": "above_ema9", "title": "Performance by EMA9 Condition", "section": "STRATEGY", "feature": "above_ema9",
     "sort": ["above", "not_above"], "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True},
    {"key": "volume_confirmed", "title": "Performance by Volume Confirmation", "section": "STRATEGY",
     "feature": "volume_confirmed", "sort": ["confirmed", "not_confirmed"], "default_metric": "net_pnl",
     "availability_timing": "PRE_ENTRY", "exclude_missing": True},
    {"key": "suggested_shares", "title": "Performance by Suggested Position Size", "section": "STRATEGY",
     "feature": "suggested_shares_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True},
    {"key": "planned_position_value", "title": "Performance by Planned Position Value", "section": "STRATEGY",
     "feature": "planned_position_value_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True},
    {"key": "planned_exposure", "title": "Performance by Planned Exposure %", "section": "STRATEGY",
     "feature": "planned_exposure_bucket", "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY",
     "exclude_missing": True},
    {"key": "mechanical_exit_reason", "title": "Performance by Copilot Exit Reason", "section": "STRATEGY",
     "feature": "mechanical_exit_reason", "default_metric": "net_pnl", "availability_timing": "EXIT",
     "exclude_missing": True, "description": "Mechanical exit reason from Pine EXIT event."},
    # RISK (Step 7)
    {"key": "r_outcome", "title": "R Outcome Distribution", "section": "RISK", "feature": "r_outcome_bucket",
     "sort": [b[0] for b in R_BUCKETS], "default_metric": "trade_count", "availability_timing": None,
     "exclude_missing": True, "description": "Retrospective R outcome. Not a pre-entry feature."},
    {"key": "initial_risk_dollar", "title": "Performance by Initial Risk $", "section": "RISK",
     "feature": "initial_risk_bucket", "sort": [b[0] for b in INITIAL_RISK_BUCKETS], "default_metric": "net_pnl",
     "availability_timing": "PRE_ENTRY", "exclude_missing": True},
    {"key": "risk_pct_equity", "title": "Performance by Risk % Equity", "section": "RISK",
     "feature": "risk_pct_equity_bucket", "sort": [b[0] for b in RISK_PCT_EQUITY_BUCKETS],
     "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY", "exclude_missing": True},
    {"key": "stop_distance", "title": "Performance by Stop Distance %", "section": "RISK",
     "feature": "stop_distance_pct_bucket", "sort": [b[0] for b in STOP_DISTANCE_BUCKETS],
     "default_metric": "net_pnl", "availability_timing": "PRE_ENTRY", "exclude_missing": True},
]

METRICS = [
    {"key": "net_pnl", "label": "Total P&L"},
    {"key": "avg_trade", "label": "Average Trade"},
    {"key": "win_rate", "label": "Win Rate"},
    {"key": "trade_count", "label": "Trade Count"},
    {"key": "avg_winner", "label": "Avg Winner"},
    {"key": "avg_loser", "label": "Avg Loser"},
    {"key": "average_mfe_r", "label": "Average MFE R"},
    {"key": "average_mae_r", "label": "Average MAE R"},
    {"key": "average_exit_efficiency", "label": "Average Exit Efficiency %"},
    {"key": "average_r_left", "label": "Average R Left on Table"},
    {"key": "average_peak_giveback", "label": "Average Peak Giveback %"},
    {"key": "average_time_to_mfe", "label": "Average Time to MFE (sec)"},
    {"key": "average_r", "label": "Average R"},
    {"key": "total_r", "label": "Total R"},
    {"key": "r_profit_factor", "label": "R Profit Factor"},
    {"key": "r_coverage_pct", "label": "R Coverage"},
]

LABEL_MAPS = {
    "day_of_week": {w[0]: w[1] for w in WEEKDAYS},
    "duration": {b[0]: b[1] for b in DURATION_BUCKETS_SEC},
    "entry_price": {b[0]: b[1] for b in ENTRY_PRICE_BUCKETS},
    "quantity": {b[0]: b[1] for b in QUANTITY_BUCKETS},
    "position_value": {b[0]: b[1] for b in POSITION_VALUE_BUCKETS},
    "daily_pnl_state": {b[0]: b[1] for b in DAILY_PNL_STATE_BUCKETS},
    "trade_number": {"1": "Trade #1", "2": "Trade #2", "3": "Trade #3", "4": "Trade #4", "5_plus": "Trade #5+"},
    "prev_outcome": {"FIRST": "First / No Previous", "WIN": "After Winner", "LOSS": "After Loser", "BREAKEVEN": "After Breakeven"},
    "consec_losses": {"0": "0 losses", "1": "1 loss", "2": "2 losses", "3_plus": "3+ losses"},
    "entry_style": {"single": "Single Entry", "scale_in": "Scale-In"},
    "exit_style": {"single": "Single Exit", "scale_out": "Partial / Scale-Out"},
    "outcome": {"WIN": "Winner", "LOSS": "Loser", "BREAKEVEN": "Breakeven"},
    "source": {"MANUAL": "MANUAL", "AUTO": "AUTO"},
    "direction": {"LONG": "LONG", "SHORT": "SHORT"},
    "entry_hour": {f"{h:02d}": f"{h:02d}:00" for h in range(7, 16)} | {"16_plus": "16:00+"},
    "opening_gap_bucket": {b[0]: b[1] for b in GAP_BUCKETS},
    "day_volume_bucket": {b[0]: b[1] for b in VOLUME_BUCKETS},
    "rvol50_bucket": {b[0]: b[1] for b in RVOL_BUCKETS},
    "prior_rvol_bucket": {b[0]: b[1] for b in PRIOR_RVOL_BUCKETS},
    "movement_bucket": {b[0]: b[1] for b in MOVEMENT_BUCKETS},
    "atr14_bucket": {b[0]: b[1] for b in ATR_BUCKETS},
    "entry_atr_bucket": {b[0]: b[1] for b in ENTRY_ATR_BUCKETS},
    "tr_atr_bucket": {b[0]: b[1] for b in TR_ATR_BUCKETS},
    "entry_sma20_bucket": {b[0]: b[1] for b in SMA_DIST_BUCKETS},
    "entry_sma50_bucket": {b[0]: b[1] for b in SMA_DIST_BUCKETS},
    "day_type": DAY_TYPE_LABELS,
    "market_movement_bucket": {b[0]: b[1] for b in MARKET_MOVEMENT_BUCKETS},
    "market_gap_bucket": {b[0]: b[1] for b in MARKET_GAP_BUCKETS},
    "market_day_type": DAY_TYPE_LABELS,
    "peak_giveback_bucket": {b[0]: b[1] for b in PEAK_GIVEBACK_BUCKETS},
    "mfe_r_bucket": {b[0]: b[1] for b in MFE_R_BUCKETS},
    "mae_r_bucket": {b[0]: b[1] for b in MAE_R_BUCKETS},
    "exit_efficiency_bucket": {b[0]: b[1] for b in EXIT_EFFICIENCY_BUCKETS},
    "r_left_bucket": {b[0]: b[1] for b in R_LEFT_BUCKETS},
    "time_to_mfe_bucket": {b[0]: b[1] for b in TIME_TO_MFE_BUCKETS},
    "time_to_mae_bucket": {b[0]: b[1] for b in TIME_TO_MFE_BUCKETS},
    "mfe_to_exit_bucket": {b[0]: b[1] for b in MFE_TO_EXIT_BUCKETS},
    "pnl_bucket": {
        "lt_neg_500": "< -$500",
        "neg_500_200": "-$500 to -$200",
        "neg_200_50": "-$200 to -$50",
        "neg_50_0": "-$50 to $0",
        "zero": "$0",
        "0_50": "$0 to $50",
        "50_200": "$50 to $200",
        "200_500": "$200 to $500",
        "gt_500": "> $500",
    },
    "signal_gap_bucket": {b[0]: b[1] for b in SIGNAL_GAP_BUCKETS},
    "signal_rvol_bucket": {b[0]: b[1] for b in SIGNAL_RVOL_BUCKETS},
    "impulse_bucket": {b[0]: b[1] for b in IMPULSE_BUCKETS},
    "retracement_bucket": {b[0]: b[1] for b in RETRACEMENT_BUCKETS},
    "above_vwap": {"above": "Above VWAP", "not_above": "Not Above VWAP"},
    "above_ema9": {"above": "Above EMA9", "not_above": "Not Above EMA9"},
    "volume_confirmed": {"confirmed": "Volume Confirmed", "not_confirmed": "Not Confirmed"},
    "initial_risk_bucket": {b[0]: b[1] for b in INITIAL_RISK_BUCKETS},
    "risk_pct_equity_bucket": {b[0]: b[1] for b in RISK_PCT_EQUITY_BUCKETS},
    "stop_distance_pct_bucket": {b[0]: b[1] for b in STOP_DISTANCE_BUCKETS},
    "r_outcome_bucket": {b[0]: b[3] for b in R_BUCKETS},
}

FUTURE_SECTIONS = [
    {"key": s[0], "label": s[1], "available": s[2], "requires": s[3] if len(s) > 3 else None, "reports": []}
    for s in SECTIONS if not s[2] and s[0] not in ("MARKET", "EXECUTION", "STRATEGY", "RISK")
]
