"""Deterministic Pine Signal ID helpers.

Canonical rule (matches Momentum_Pullback_Copilot_SIGNALLOG.pine):

    <STRATEGY_KEY>|<TICKER>|<TIMEFRAME>|<OPPORTUNITY_BIRTH_BAR_MS>

OPPORTUNITY_BIRTH_BAR_MS is the ARMED bar timestamp (milliseconds) for
strategies with an ARMED lifecycle. Strategies without ARMED use ENTRY bar ms.

The ID is generated by Pine at ARMED and reused for ARMED / ENTRY / EXIT.
The analyzer never re-derives it; it stores the Pine value verbatim.
"""

from __future__ import annotations

import re

_VERSION_RE = re.compile(r"v?\d+(?:\.\d+)+", re.IGNORECASE)


def build_signal_id(strategy_key: str, ticker: str, timeframe: str, birth_bar_ms: int | str) -> str:
    return f"{strategy_key}|{ticker}|{timeframe}|{birth_bar_ms}"


def parse_signal_id(signal_id: str) -> dict[str, str] | None:
    parts = (signal_id or "").split("|")
    if len(parts) < 4:
        return None
    return {
        "strategy_key": parts[0],
        "ticker": parts[1],
        "timeframe": parts[2],
        "birth_bar_ms": parts[3],
    }


def normalize_strategy_version(raw: str | None) -> str:
    """Stable analytics key. Original string is preserved separately on Signal."""
    if not raw:
        return ""
    text = raw.strip()
    match = _VERSION_RE.search(text)
    if not match:
        return text
    token = match.group(0)
    if not token.lower().startswith("v"):
        token = "v" + token
    return token.lower() if token[:1] in "vV" else token
